on:
  push:

jobs:
  deploy:
    name: "Deploy KAPLAYGROUND on Cloudflare Workers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_KEY }}
          command: pages deploy dist --project-name=kaplay
          preCommands: "pnpm i && pnpm build"
